opt_out_usage
default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Release a new version to internal testers"
  lane :deploy do
    gradle(task: "bundle", build_type: "Release")
    upload_to_play_store(
      track: "internal",
      release_status: "draft"
    )
  end

  desc "Deploy a new version to the Google Play Store"
  lane :playstore do
    gradle(task: "bundle", build_type: "Release")
    upload_to_play_store
  end
end
